/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package libstemmerexample

import org.tartarus.snowball.SnowballStemmer
import org.tartarus.snowball.ext.englishStemmer

fun main(args: Array<String>) {
    val stemmer: SnowballStemmer = englishStemmer()

    val words = listOf(
        "apples", "boxes", "countries", "indcies", "knives", "men", "going",
        "gone", "went", "playing", "played", "have", "has", "had", "hidden"
    )

    for (word in words) {
        stemmer.setCurrent(word)
        stemmer.stem()
        println("%s -> %s".format(word, stemmer.getCurrent()))
    }
}
